# Use Node image
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy package files first (better caching)
COPY package*.json ./

# Install dependencies
RUN pnpm install

# Copy rest of the app
COPY . .

# Build TypeScript
RUN pnpm run build

# Expose port
EXPOSE 3000

# Run app
CMD ["node", "dist/server.js"]